### ISSUE TITLE
error: the cryptoggraphic signature of "/mnt/gentoo//stage3-*.tar.bz2.DIGESTS.asc" cloud not be verified!

### ISSUE THREAD

**Issue by appath** [nathanshearer/gentooinstall#1]
Hi
The problem with checking the script is
error: the cryptoggraphic signature of "/mnt/gentoo//stage3-*.tar.bz2.DIGESTS.asc" cloud not be verified!
checked swap key 0xBB572E0E2D182910

.tar.{bz2,xz}
In the code bz2

**Comment by nathanshearer** [comment]
The fix has been committed. Please let me know if it is working for you now.

**Comment by appath** [comment]
He checks the keys and the hash, too.
But the problem is different now, the port is not \tmp\gentooinstall not files
I look in the code there is a partition for disks or I am mistaken in what that.

**Comment by nathanshearer** [comment]
The partition phase is disabled by default. What error do you get when running the script? Are you trying to resume an install or does this happen with a new install?

**Comment by appath** [comment]
new install

**Comment by nathanshearer** [comment]
What error do you get when running the script?
